name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: "ubuntu-18.04"
    defaults:
      run:
        working-directory: ./full-stack-open-pokedex
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"
      - name: testing directory list
        run: ls
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./full-stack-open-pokedex
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.11.10
        with:
          appdir: ./full-stack-open-pokedex
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key:
            # Email that you use with heroku
            ${{secrets.HEROKU_API_KEY}}
          heroku_email: richardhenninger@live.com
          heroku_app_name:
            # An optional buildpack to use when creating the heroku application
            richen-fso2020-pokedex
          healthcheck: "https://richen-fso2020-pokedex.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
